github:
  client:
    id: e0101a1b542cab3430d7
    secret: 56cfaf8b28078b272381650f3f7be3931a531d53
  redirect:
    uri: http://localhost:8080/callback

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf8
    username: root
    password: sa
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: mapper/*.xml